BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_number
            text: "34"
            font_size: 48
        BoxLayout:
            orientation: 'vertical'
            size_hint_x: 0.20
            Button:
                text: "Up"
            Button:
                text: "Down"
    Button:
        text: "Convert miles to km"
    Label:
        id: output_label
        font_size: 48
        color: (1, 1, 0, 1)